const ROUTES = {
  LogIn: '/login',
  Register: '/register',
  ResetPasswordToken: '/reset-password/:token',
  Accounts: '/accounts',
  CityAdmin: '/user-management',
  Tiles: '/tiles',
  UploadTile: 'upload',
  EditTile: 'upload/:id',
  TileListing: 'listing',
  Categories: '/categories',
  CityCategory: 'city',
  UpdateCityCategory: 'update/:cityId/:categoryId',
  CreateCategory: 'create',
  CreateCityCategory: 'create/city',
  UpdateCategory: 'update/:categoryId',
  CategoryListing: 'listing',
  Unauthorized: '/unauthorized',
  Dummy: '/dummy',
  PrivacyPolicy: '/privacy',
  TermsConditions: '/terms',
  Default: '/',
  NotFound: '*',
  Dashboard: '/dashboard',
  Listings: '/listings',
  UploadListing: 'upload-list',
  UpdateListing: 'update-list/:listingId',
  Lists: 'lists',
} as const;

export default ROUTES;
