const API_URLS = {
  LogIn: 'auth/login',
  LogOut: 'auth/logout',
  RefreshToken: 'auth/refresh',
  ValidateResetPasswordToken: 'auth/validate',
  Register: 'users/register',
  GetAdminListing: 'users/',
  Account: 'users',
  Profile: 'users/profile/me',
  UpdateUserPassword: 'users/profile/me/change-password',
  GetAllTiles: 'core/tiles',
  Tiles: 'core/tiles',
  DeleteUser: 'users/',
  UpdateUser: 'users/',
  AssignRole: 'auth/assign-city-admin',
  GetAllCities: 'city/',
  ResetPassword: 'users/reset-password/request',
  ConfirmResetPassword: 'users/reset-password/confirm',
  RestoreUser: 'users/:id/restore',
  Listings: 'core/listings',
  GetCityCategories: '/core/categories/cities',
  GetTags: 'core/tags',
  HeroImage: 'hero-image',
  Media: 'media',
  CreateCategory: 'core/categories',
  GetLatestTermsAndConditions: 'users/terms/latest',
} as const;

export default API_URLS;
